# Generated by Django 4.1.7 on 2023-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=300)),
                ('number', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
