# Generated by Django 4.1.7 on 2023-04-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='c_name',
            new_name='name',
        ),
    ]
